# Generated by Django 6.0.7 on 2026-08-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_alter_teammember_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["username"],
                "verbose_name": "team member",
                "verbose_name_plural": "team members",
            },
        ),
        migrations.AlterField(
            model_name="teammember",
            name="years_of_experience",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
